### ISSUE TITLE
The ability to reset the melody and immediately the subject

### ISSUE THREAD

**Issue by Paradox75831004** [ZigzagAwaka/ChillaxScraps#1]
When the animation of the melody begins - can't you reset or cancel anything, is that what it's supposed to be?
I mean, why can't you reset the item earlier and set the melody?

![image](https://github.com/user-attachments/assets/69e85552-df2d-4e39-b89e-6688432db46c)

**Comment by ZigzagAwaka** [comment]
Yep that's not supposed to be changed when playing music
But i didn't understood what you want, do you want a way to set melodies while already playing a song? Or a way to cancel the melody ?

**Comment by Paradox75831004** [comment]
> Да, это не должно меняться во время воспроизведения музыки. Но я не понял, что вы хотите, вы хотите способ устанавливать мелодии во время воспроизведения песни? Или способ отменить мелодию?

the ability to stop the melody

**Comment by ZigzagAwaka** [comment]
Ok, how would you like me to add this ability ?
For example, i can make it so if you use the item again (LMB) while already playing music this cancels the effect, what do you think ?

**Comment by ZigzagAwaka** [comment]
Oh i have a better idea, i will try to make the ocarina as a "hold button use" item, so as long as you press the button it will play music and when you release it will stop

**Comment by ZigzagAwaka** [comment]
Added in the latest 1.1.1 update, thanks for playing the mod !

**Comment by Paradox75831004** [comment]
> О, у меня есть идея получше: я попробую сделать окарину предметом, позволяющим удерживать кнопку, чтобы, пока вы нажимаете кнопку, она воспроизводила музыку, а когда вы отпустите, она прекращалась.

That's fine)
The duration of the melody is still small, the player will not get tired of holding the LMB xD

**Comment by Paradox75831004** [comment]
> Oh i have a better idea, i will try to make the ocarina as a "hold button use" item, so as long as you press the button it will play music and when you release it will stop

That's fine)
The duration of the melody is still small, the player will not get tired of holding the LMB xD
