### ISSUE TITLE
Change the mechanics of the bird

### ISSUE THREAD

**Issue by Paradox75831004** [ZigzagAwaka/ChillaxScraps#2]
Make it possible for it to be on the battery. And so that she not only pushes forward, but also other parties (let people suffer, and not abuse her)
![image](https://github.com/user-attachments/assets/3bddacf5-e547-47e4-9f1b-8999530ad9ac)

**Comment by ZigzagAwaka** [comment]
So making it as a battery item + can also inflict knocback on other players right? Sure i will look into adding that

**Comment by Paradox75831004** [comment]
> So making it as a battery item + can also inflict knocback on other players right? Sure i will look into adding that

To throw it in different directions, and not just forward - only the one who holds it in his hands and uses it.

**Comment by ZigzagAwaka** [comment]
Oh i see
I will make this as a random chance so this will surprise peoples

**Comment by ZigzagAwaka** [comment]
Added in 1.2.0, thanks for playing !
